import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { useSession } from "next-auth/react";

import { api } from "@/utils/api";
import AuthShowcase from "@/components/showAuthCase";
import { type ChangeEvent, useState } from "react";

const Home: NextPage = () => {
  const { data: sessionData } = useSession();
  const { data: restaurant, isLoading: isFetching } = useGetAllUserRestaurants(
    sessionData?.user.id
  );
  const { mutate, isLoading: isCreating } = useCreateRestaurant(
    sessionData?.user.id
  );
  const [title, setTitle] = useState("");
  const [description, setDescription] = useState("");

  if (!sessionData || !sessionData.user) return <h1>Loading...</h1>;

  if (isFetching) return <h1>Loading...</h1>;

  function handleSubmit(e: ChangeEvent<HTMLFormElement>) {
    e.preventDefault();
    mutate({ title, description, userId: sessionData?.user.id || "" });
  }

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <nav>
        <AuthShowcase sessionData={sessionData} />
      </nav>
      <main className="justify-centerbg-gradient-to-b flex min-h-screen flex-col items-center">
        {restaurant ? (
          <div>
            <p className="text-2xl font-bold">My Store</p>
            <p className="text-4xl font-bold">{restaurant?.title}</p>
            <p className="text-2xl font-semibold">{restaurant?.description}</p>
            <p>Other details</p>
            <Link
              href={{
                pathname: "/app/menu",
                query: { restaurantId: restaurant.id },
              }}
            >
              <div className="rounded-full bg-white/10 px-10 py-2 text-center">
                Create Menu
              </div>
            </Link>
          </div>
        ) : (
          <>
            <div>
              <p>Create your shop and start earning</p>
              <div className="rounded-full bg-white/10 px-10 py-3 font-semibold text-white no-underline transition">
                Create shop
              </div>
            </div>

            <form className="w-1/2" onSubmit={handleSubmit}>
              <div>
                <input
                  type="text"
                  value={title}
                  onChange={(e) => setTitle(e.target.value)}
                  placeholder="shop name"
                  className="my-2 w-full p-2 text-black outline-none"
                />
              </div>
              <div>
                <input
                  type="text"
                  value={description}
                  onChange={(e) => setDescription(e.target.value)}
                  placeholder="shop description"
                  className="my-2 w-full p-2 text-black outline-none"
                />
              </div>
              <button
                type="submit"
                disabled={isCreating}
                className="rounded-full bg-white/10 px-10 py-3 font-semibold text-white no-underline transition hover:bg-white/20"
              >
                Create
              </button>
            </form>
          </>
        )}
      </main>
    </>
  );
};

export default Home;

function useGetAllUserRestaurants(userId?: string | "") {
  return api.restaurant.show.useQuery({
    userId: userId || "",
  });
}

function useCreateRestaurant(userId?: string) {
  const utils = api.useContext();

  return api.restaurant.create.useMutation({
    onSuccess: async () => {
      await utils.restaurant.show.invalidate({ userId: userId || "" });
    },
  });
}
