import Head from "next/head";
import Link from "next/link";
import { useSession } from "next-auth/react";
import AuthShowcase from "@/components/showAuthCase";

export default function MenuPage() {
  const { data: sessionData } = useSession();
  if (!sessionData || !sessionData.user) return <h1>Loading...</h1>;

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <nav>
        <AuthShowcase sessionData={sessionData} />
      </nav>
      <main className="justify-centerbg-gradient-to-b flex min-h-screen flex-col items-center"></main>
    </>
  );
}
