import Head from "next/head";
import { useSession } from "next-auth/react";
import AuthShowcase from "@/components/showAuthCase";
import { type ChangeEvent, useState } from "react";
import axios from "axios";
import { api } from "@/utils/api";
import { useMutation } from "@tanstack/react-query";
import { restaurantDefaultSchema } from "@/api-contract/restautant.schema";
import { useRouter } from "next/router";
import { type Menu } from "@/api-contract/menu.schema";
import { H4, P } from "@/components/ui/typography";
import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";
import { Menubar } from "@radix-ui/react-menubar";

export default function MenuPage() {
  const { query } = useRouter();
  const restaurantId = query.restaurantId as string;
  const [file, setFile] = useState<File>();
  const { data: sessionData } = useSession();
  const { data: menus } = useGetRestaurantMenu(restaurantId);
  const createMenu = useCreateMenu();
  if (!sessionData || !sessionData.user) return <h1>Loading...</h1>;

  const onFileChange = (e: ChangeEvent<HTMLInputElement>) => {
    if (e.target.files && e.target.files.length > 0) {
      setFile(e.target.files[0]);
    }
  };

  const onHandleUpload = () => {
    if (file) {
      createMenu.mutate(
        { file, restaurantId },
        {
          onSuccess: () => {
            setFile(undefined);
          },
        }
      );
    }
  };

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Menubar>
        <AuthShowcase sessionData={sessionData} />
      </Menubar>
      <main className="justify-centerbg-gradient-to-b flex min-h-screen flex-col items-center">
        <div className="flex flex-col items-center">
          <H4>
            Do not stress, Just Upload your pdf menu. We shall do the rest.
          </H4>
          <label
            htmlFor="file"
            className="cursor-pointer rounded-full bg-white px-5 py-2 text-black hover:bg-white/10 hover:text-white"
          >
            Upload
          </label>
          {file && <p className="ml-2 mt-2 text-sm">{file.name}</p>}
          <Input
            id="file"
            type="file"
            accept="application/pdf"
            onChange={onFileChange}
            className="hidden"
          />

          <Button
            className="mt-10 block rounded-full bg-white/10 px-10"
            onClick={() => void onHandleUpload()}
          >
            {createMenu.isLoading ? <P>Loading....</P> : <P>Save</P>}
          </Button>
        </div>
        {menus && (
          <div className="w-1/2">
            {menus.map((menu) => (
              <MenuComponent key={menu.id} menu={menu} />
            ))}
          </div>
        )}
      </main>
    </>
  );
}

function useGetRestaurantMenu(restaurantId: string) {
  return api.menu.list.useQuery({ id: restaurantId });
}

function useCreateMenu() {
  const utils = api.useContext();

  const createMenu = async (data: { file: File; restaurantId: string }) => {
    const formdata = new FormData();
    formdata.append("file", data.file);
    formdata.append("restaurantId", data.restaurantId);
    const response = await axios.post("/api/file-upload/create", formdata, {
      headers: { "Content-Type": "multipart/form-data" },
    });

    return restaurantDefaultSchema.parse(response.data);
  };

  return useMutation(createMenu, {
    onSuccess: async () => {
      await utils.menu.list.invalidate();
    },
  });
}

function MenuComponent({ menu }: { menu: Menu }) {
  return (
    <div className="w-full">
      <H4>{menu.title}</H4>
      <div>
        {menu.items.map((item) => (
          <div
            className="my-2 flex w-full items-center justify-between border-b border-slate-500 py-2"
            key={item.id}
          >
            <P>{item.title}</P>
            <P>${item.price}</P>
          </div>
        ))}
      </div>
    </div>
  );
}
